# Generated by Django 5.1.5 on 2026-05-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('scope', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=80)),
                ('activity_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('original_unit', models.CharField(max_length=20)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('normalized_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=14)),
                ('co2e_emissions', models.DecimalField(decimal_places=3, max_digits=14)),
                ('review_status', models.CharField(choices=[('PENDING', 'PENDING'), ('FLAGGED', 'FLAGGED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.company')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='ingestion.rawrecord')),
            ],
        ),
    ]
